dog/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('recommendation/', views.recommendation_view, name='recommendation'),
    path('recommendation_results/', views.recommendation_results, name='recommendation_results'),
]

dogshopmall/urls.py
from django.contrib import admin
from django.urls import path, include
from dogshopmall.views import HomeView
from django.conf import settings
from django.conf.urls.static import static
from product import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('user/', include('user.urls')),
    path('dog/', include('dog.urls')),    
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
# order/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('order_list/', views.order_list, name='order_list'),
    # 다른 URL 패턴들을 여기에 추가할 수 있습니다.
    path('order_create/', views.order_create, name='order_create'),  # 추가

]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'user'

urlpatterns = [
    path('registration/', views.register, name='registration'),  # 'register' 뷰를 사용하도록 지정
    path('login/', LoginView.as_view(template_name='user/login_view.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='user/logout.html'), name='logout'),
]

order/models.py
from django.db import models
from user.models import User
from product.models import Product


# Create your models here.
pay_type = (
    ('a', '계좌이체'),
    ('b', '무통장 입금'),
    ('c', '카드'),
)
class Order(models.Model):

    order_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now_add=True)
    address = models.CharField(max_length=100, null=True, blank=True, default="")
    request = models.TextField(blank=True) 
    pay = models.CharField(max_length=10, choices=pay_type)

    class Meta:
        db_table = 'my_order'

class Order_Detail(models.Model):
    pay_type = (
        ('a', '계좌이체'),
        ('b', '무통장 입금'),
        ('c', '카드'),
    )
    
    order_detial_id = models.AutoField(primary_key=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    # order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True) # 상품 참조 추가
    price = models.IntegerField()
    count = models.IntegerField()
    pay = models.CharField(max_length=10, choices=pay_type)
    # address = models.CharField(max_length=100)

    class Meta:
        db_table = 'my_order_detail'

order/forms.py
from django import forms
from .models import Order, Order_Detail
from cart.models import Cart

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'request']
        labels = {
            'address': '주소',
            'request': '요청사항',
        }

class OrderDetailForm(forms.ModelForm):
    class Meta:
        model = Order_Detail
        fields = ['product', 'price', 'count', 'pay']
        labels = {
            'product': '상품',
            'price': '가격',
            'count': '수량',
            'pay': '결제수단',
        }



# forms.py
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'request','pay']
        labels = {
            'address': '주소',
            'request': '요청사항',
        }

    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['pay'] = forms.ChoiceField(choices=Order_Detail.pay_type, label='결제수단')

    def save(self, commit=True):
        order = super().save(commit=False)
        if commit:
            order.save()
            for item in Cart.objects.filter(user=order.user):
                pay_value = next((display for value, display in Order_Detail.pay_type if value == self.cleaned_data['pay']), None)
                Order_Detail.objects.create(
                    order=order, 
                    product=item.product_id, 
                    count=item.count, 
                    price=item.product_id.price,
                    pay= order.pay,
                )
        return order

order/views.py
# order/views.py
from django.shortcuts import render, redirect
from .models import Order, Order_Detail
from product.models import Product
from django.contrib.auth.decorators import login_required
from cart.models import Cart
from .forms import OrderForm, OrderDetailForm
from .forms import OrderCreateForm


# views.py
def order_list(request):
    user_orders = Order.objects.filter(user=request.user)
    user_order_details = Order_Detail.objects.filter(order__in=user_orders)

    return render(request, 'order/order_list.html', {'user_orders': user_orders, 'user_order_details': user_order_details})


def order_list2(request):
    user_orders2 = Product.objects.values('product_id','name','brand','image')
    
    return render(request, 'order/order_list.html', {'user_orders2': user_orders2})

@login_required
def order_create(request):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.product_id.price * item.count for item in cart_items)

    if request.method == 'POST':
        order_form = OrderCreateForm(request.POST)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.user = request.user
            order.save()

            for item in cart_items:
                Order_Detail.objects.create(order=order, product=item.product_id, count=item.count, price=item.product_id.price)

            cart_items.delete()

            return redirect('order_list')
    else:
        order_form = OrderCreateForm()

    context = {'order_form': order_form, 'cart_items': cart_items, 'total_price': total_price}
    return render(request, 'order/order_create.html', context)

order/templates/order/order_create.html
{% load static %}

<style>
    /* 테이블 스타일을 조정하는 CSS */
    table {
        width: 35%;
        border-collapse: collapse;
    }

    th, td {
        padding: 13px;
        text-align: left;
        border: 1px solid #dfdede;
    }

    th {
        background-color: #dfdede;
    }

    h2 {
        margin-top: 40px;
    }

    .total-label {
        font-size: 19px;
    }

    .total-price {
        font-size: 19px;
        color: red;
    }

    /* 각 섹션 사이의 간격을 조정하는 CSS */
    .section {
        margin-bottom: 30px;
    }

    .submit-button {
        background-color: red;  /* 버튼의 배경색을 빨간색으로 설정 */
        color: white;  /* 버튼의 텍스트 색상을 흰색으로 설정 */
        padding: 10px 20px;  /* 버튼의 패딩을 설정 */
        border: none;  /* 버튼의 테두리를 없애기 */
        cursor: pointer;  /* 마우스 커서를 포인터로 변경 */
    }

    /* '주문하기' 버튼에 마우스를 올렸을 때의 스타일을 지정하는 CSS */
    .submit-button:hover {
        background-color: darkred;  /* 버튼의 배경색을 더 어두운 빨간색으로 변경 */
    }
    /* 웹페이지의 내용을 중앙에 정렬하는 CSS */
    .box {
        width: 290%;  /* 컨테이너의 너비를 설정. 필요에 따라 값을 조정하십시오. */
        margin: 00%;  /* 가로 방향으로 자동 마진을 적용 */
    }

    /* 입력 필드의 크기를 조정하는 CSS */
    .input-field {
        width: 10%;  /* 입력 필드의 너비를 부모 요소의 100%로 설정 */
        height: 40px;  /* 입력 필드의 높이를 40px로 설정 */
        margin-bottom: 20px;
        
    }

    textarea.input-field {
        height: 20%;  /* textarea 필드의 높이를 자동으로 설정 */
    }

    /* '주문하기' 버튼의 너비를 고정하는 CSS */
    .submit-button {
        width: 100px;  /* '주문하기' 버튼의 너비를 150px로 고정 */
        /* ... 기타 스타일 ... */
    }



</style>

<div class="box container">
    <div class="section">
        <h2>주문서조회</h2>
        <table>
            <thead>
                <tr>
                    <th>사료명</th>
                    <th>수량</th>
                    <th>가격</th>
                    <th>이미지</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.product_id.name }}</td>
                    <td>{{ item.count }}</td>
                    <td>{{ item.product_id.price }}</td>
                    <td>
                        <img src="{% static item.product_id.image %}" alt="{{ item.product_id.name }}" width="100" height="100">
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h4><span class="total-label">총 금액: </span><span class="total-price">{{ total_price }}원</span></h4>
    </div>

    <form method="POST">
        {% csrf_token %}
        <div class="section">
            <h2>배송지정보입력</h2>
            <div>
                <div>{{ order_form.address.label_tag }}</div> <input type="text" name="address" class="input-field">
            </div>
            <div>
                <div>{{ order_form.request.label_tag }}</div>  <!-- '요청사항' 라벨을 div로 감싸기 -->
                <textarea name="request" class="input-field"></textarea>
            </div>
        </div>
        <div class="section">
            <h2>결제수단선택</h2>
            <div>
                {{ order_form.pay.label_tag }}
                {{ order_form.pay }}
            </div>
        </div>
        <input type="submit" value="결제하기" class="submit-button">  <!-- '주문하기' 버튼에 class를 추가 -->
    </form>
</div>

order/templates/order/order_list.html
<!-- order/templates/order/order_list.html -->
{% extends "base.html" %}
{% load static %}

{% block title %}주문 조회{% endblock %}

{% block header %}
<header class="header_section">
    <nav class="navbar navbar-expand-lg custom_nav-container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <span> 개밥천국 </span>
      </a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class=""></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}"
              >홈 <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recommendation' %}"> 사료 추천 </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'product_view' %}"> 사료 정보 </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'order_list' %}"> 주문 조회 </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user:registration' %}"> 회원가입 </a>
          </li>
        </ul>
        <div class="user_option">
          <a href="{% url 'user:login' %}">
            <i class="fa fa-user" aria-hidden="true"></i>
            <span> 로그인 </span>
          </a>
          <a href="{% url 'cart_items' %}">
            <i class="fa fa-shopping-bag" aria-hidden="true"></i>
          </a>
          <form class="form-inline">
            <button class="btn nav_search-btn" type="submit">
              <i class="fa fa-search" aria-hidden="true"></i>
            </button>
          </form>
        </div>
      </div>
    </nav>
  </header>
{% endblock %}

{% block content %}
<div class="box container">
    <h3>주문 조회</h3>
    <table style="width: 160%; table-layout: fixed;">
  
        <thead>
            <tr>
                {% comment %} <th>주문 번호</th> {% endcomment %}
            <!-- 각 th에 패딩을 추가 -->
              <th style="padding-right: 20px;">주문 일자</th>
              <th style="padding-right: 20px;">상품 코드</th>
              <th style="padding-right: 20px;">상품 이름</th>
              <th style="padding-right: 20px;">상품 브랜드</th>
              <th style="padding-right: 20px;">상품 가격</th>
              <th style="padding-right: 20px;">상품 이미지</th>
            </tr>
        </thead>
        <tbody>
            {% for order in user_orders %}
            {% for detail in order.order_detail_set.all %}
            <tr>
              {% comment %} <td>{{ order.order_id }}</td> {% endcomment %}
              <td>{{ order.create_dt }}</td>
              <td>{{ detail.product.product_id }}</td>
              <td>{{ detail.product.name }}</td>
              <td>{{ detail.product.brand }}</td>
              <td>{{ detail.price }}</td>
              {% comment %} <td><img src="{{ detail.product.image.url }}" alt="{{ detail.product.name }}" width="100" height="100"></td> {% endcomment %}
              {% comment %} <td><img src="{% static detail.product.image.url %}" alt="{{ detail.product.name }}" width="80" height="80"></td> {% endcomment %}
              <td><img src="{% static detail.product.image %}" alt="{{ detail.product.name }}" width="100" height="100"><td>
              {% comment %} <td>{{ detail.price }}</td> {% endcomment %}
            </tr>
            {% endfor %}
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}